# Generated by Django 3.2.6 on 2021-11-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='decryption_type',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='encryption_type',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='decryption_algorithms',
            field=models.CharField(choices=[('NA', 'NA'), ('Vigenère cipher', 'Vigenère cipher'), ('One Time Pad', 'One Time Pad'), ('AES (Advanced Encryption Standard)', 'AES (Advanced Encryption Standard)'), ('RSA Security', 'RSA Security')], default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='encryption_algorithms',
            field=models.CharField(choices=[('NA', 'NA'), ('Vigenère cipher', 'Vigenère cipher'), ('One Time Pad', 'One Time Pad'), ('AES (Advanced Encryption Standard)', 'AES (Advanced Encryption Standard)'), ('RSA Security', 'RSA Security')], default='NA', max_length=50),
        ),
    ]
