# Generated by Django 3.2.6 on 2021-11-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211105_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='processed_file_link',
            field=models.CharField(default='none 2', max_length=255),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='processed_file_name',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
